### ISSUE TITLE
[🐛 Bug] 当系统时间为国庆节之后时，使用 fcnearly 命令会导致报错崩溃

### ISSUE THREAD

**Issue by azaz-az** [azaz-az/holiday-predictor#29]
## 检查项

- ✅ 我已在[Issues](https://github.com/azaz-az/holiday-predictor/issues)中搜索，确认这个 bug 没有被提交过。

## 基本信息

- 程序版本：v0.13.1
- 操作系统名称与版本：Windows 11 Build 26120.961
- > 如果您使用的是例如 Arch Linux 等滚动发行版，请在此填写发行版名称，无需填写版本。非滚动发行版用户则需要填写版本。例如“Debian 12.6” / “Windows 11 Build 26120.961”等
- Python 版本：3.12.3

## 详细描述

当系统时间为国庆节之后时，使用 fcnearly 命令会导致报错崩溃，如下：

```
Holiday Predictor / 假期预测器 - 基于 Python 的调休预测工具
键入 help 以查看帮助。
> fcnearly
Traceback (most recent call last):
  File "C:\Users\a233d\Documents\git\holiday-predictor\__main__.py", line 88, in <module>
    print(calculation_forecast_nearly())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a233d\Documents\git\holiday-predictor\main.py", line 227, in calculation_forecast_nearly
    '--' + str(CalculationUtil.NearlyNext.today()[1].replace('_', '-'))]))
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

进程已结束，退出代码为 1
```

**Comment by azaz-az** [comment]
已在 [v1.0.0-alpha.2](https://github.com/azaz-az/holiday-predictor/releases/tag/v1.0.0-alpha.2) 中修复。

**Comment by azaz-az** [comment]
已在 [v1.0.0](https://github.com/azaz-az/holiday-predictor/releases/tag/v1.0.0) 中修复。
